---
title: ""
author: ""
date: ""
output: html_document
---


<br>
<br>


This function will return the minimum sample size required for specified power and other model parameters for estimating association between a binary environmental exposure and a binary outcome from a case-control model:

\[ log\bigg(\frac{p}{1-p}\bigg)  = \beta_0 + \beta_1 E \]

Where $\beta_1$ is the log(OR) for the association between a the environmental exposure and case-control status.

<br>
<br>

### Input Parameters:

- Controls:Case: Number of controls for each case
- $P_e$: Prevalance of environmental risk factor in population
- $OR_e$: Odds-Ratio for enviromental risk factor in population
- Alpha: Type I error rate
- Beta: Power or 1-Type II error
- \# Tests: Number of tests to be performed (i.e. number of variants in GWAS analysis). Will use Bonferonni correction to adjust power or sample size for specified number of tests.

Notes:

_Value ranges_

You can specify either a single value for $P_e$ and $OR_e$, or a range of values, using **From:** and **To:** input boxes.

